apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: {{ .Values.app.namespace }}
  name: "backend-waf-{{ .Values.app.name }}"
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 3
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: {{ .Values.app.healthCheckPath }}