apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-app-service"
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "backend-waf-{{ .Values.app.name }}"}'
spec:
  selector:
    app: "{{ .Values.app.name }}-app"
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port }}
  type: ClusterIP
